# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: yarn global add express
    init: yarn install
    command: yarn build

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
    name: L0L1G1tP0d
    description: loligitp0d

# Image location
image:
    file: .gitpod.dockerfile
    
# Update OS
update:
  - name: Update & Upgrade
    command: sudo apt update && sudo apt upgrade -y
